# Use an official Ubuntu base image
FROM mcr.microsoft.com/devcontainers/dotnet:latest
# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    apt-transport-https \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# Install PowerShell
RUN wget http://nl.archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu72_72.1-3ubuntu3_amd64.deb \
    && dpkg -i libicu72_72.1-3ubuntu3_amd64.deb \
    && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y powershell \
    && rm -rf /var/lib/apt/lists/* \
    && rm packages-microsoft-prod.deb libicu72_72.1-3ubuntu3_amd64.deb

# Add other setup steps here if needed
